version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - todo_app-db:/data/postgres
    env_file:
      - docker.env
    networks:
      - todo_app_nw

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ~/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - todo_app_nw

  todo_app:
    image: illuque/todo_app:dev
    container_name: todo_app
    restart: unless-stopped
    env_file:
      - docker.env
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - todo_app-node_modules:/usr/src/app/node_modules
    networks:
      - todo_app_nw
    depends_on:
      - postgres

networks:
  todo_app_nw:
    driver: bridge

volumes:
  todo_app-db:
  todo_app-node_modules: